export default {
  order: 10,
  layerGroupId: 'GROUP_LCD',
  dataLayer: {
    id: 'RADD_ALERTS',
    order: 10,
    type: 'remoteDataLayer',
    uuid: '440e53d0-36b3-47ad-993a-1c2018c3942c',
    groupId: 'GROUP_LCD',
  },
  layer: {
    metadata: {
      metadata: null,
      legendConfig: {
        name: {
          ka: 'RADD შეტყობინებები',
          zh: 'RADD 预警',
          id: 'Peringatan RADD',
          pt: 'Alertas RADD',
          es: 'Alertas RADD',
          fr: 'Alertes RADD',
          en: 'RADD Alerts',
        },
        type: 'basic',
        items: [
          {
            outlineColor: '#555555',
            color: '#DC6699',
            name: {
              ka: 'RADD შეტყობინებები',
              zh: 'RADD 预警',
              id: 'Peringatan RADD',
              pt: 'Alertas RADD',
              es: 'Alertas RADD',
              fr: 'Alertes RADD',
              en: 'RADD Alerts',
            },
          },
          {
            outlineColor: '#555555',
            color: '#e4c600',
            name: {
              ka: 'ბოლო შეტყობინებები',
              zh: '最近的提醒',
              id: 'Lansiran Terbaru',
              pt: 'Alertas Recentes',
              es: 'Alertas recientes',
              fr: 'Alertes récentes',
              en: 'Recent Alerts',
            },
          },
        ],
      },
      interactionConfig: {},
    },
    sublabel: {
      ka: '(ყოველკვირეული, 30მ, აარჩიეთ ქვეყნები, UMD/ GLAD)',
      zh: '（每周，30m，热带地区，UMD/ GLAD）',
      id: '(mingguan, 30m, tropis. UMD/GLAD)',
      pt: '(semanal, 30m, trópicos, UMD/ GLAD)',
      es: '(semanal, 30m, trópicos, UMD/ GLAD)',
      fr: '(hebdomadaire, 30m, tropiques, UMD/ GLAD)',
      en: '(every 6-12 days, 10m, select countries, WUR)',
    },
    label: {
      ka: 'RADD Alerts',
      zh: 'RADD Alerts',
      id: 'RADD Alerts',
      pt: 'RADD Alerts',
      es: 'RADD Alerts',
      fr: 'RADD Alerts',
      en: 'RADD Alerts',
    },
    confidence: [0, 1],
    maxDateValue: 999999,
    minDateValue: 15000,
    technicalName: 'wur_radd_alerts',
    url: 'https://tiles.globalforestwatch.org/wur_radd_alerts/latest/default/{z}/{x}/{y}.png',
    type: 'glad',
    id: 'RADD_ALERTS',
  },
  isMetadataError: false,
  isError: false,
};
