export default {
  webmap: 'de85e3fcc07948238aa6c1afd2a4ceb0',
  title: 'GFW Mapbuilder',
  subtitle: 'Make maps that matter',
  logoUrl: '',
  logoLinkUrl: '',
  aboutLinkUrl: '',
  downloadLinkUrl: '',
  printServiceUrl: 'https://gis.forest-atlas.org/server/rest/services/print/ExportWebMap/GPServer/Export%20Web%20Map',
  maskServiceUrl: '',
  mapThemeIds: '',
  mapThemes: '',
  narrative: '',
  hideHeader: false,
  hideFooter: false,
  includeMyGFWLogin: true,
  navLinksInNewTab: false,
  customColorTheme: '',
  language: 'en',
  useAlternativeLanguage: false,
  alternativeWebmap: '',
  alternativeLanguage: 'fr',
  alternativeLanguageTitle: 'Mapbuilder',
  alternativeLanguageSubtitle: 'Make maps that matter',
  alternativeMapThemes: '',
  alternativeNarrative: '',
  alternativeWebmapMenuName: 'Custom Layers',
  initialExtent: {
    x: null,
    y: null,
    z: null,
  },
  includeDocumentsTab: false,
  iso: '',
  viirsFires: true,
  intactForests: true,
  primaryForests: true,
  forma: false,
  aboveGroundBiomass: true,
  landCover: true,
  mangroves: false,
  sadAlerts: false,
  gladAlerts: true,
  gfwIntegratedAlertLayer: true,
  recentImagery: true,
  carbonSequence: true,
  carbonEmissions: true,
  treeCoverHeight: true,
  treeCover: true,
  treeCoverGain: true,
  treeCoverLoss: true,
  treeMosaicLandscapes: true,
  forestCarbonGrossRemovals: true,
  forestCarbonGrossEmissions: true,
  forestCarbonNetFlux: true,
  umdLandCover: true,
  drySpells: true,
  airQuality: true,
  windSpeed: true,
  webmapMenuName: 'Custom Layers',
  sharinghost: 'https://www.arcgis.com',
  analyticsCode: '',
  includeCartoTemplateLayers: false,
  cartoUser: 'wri-01',
  cartoTemplateId: 'tpl_07c315f8_c13e_11e4_b457_0e8dde98a187',
  cartoApiKey: 'your key here',
  cartoGroupLabel: {
    en: 'Carto Layers',
    fr: 'Carto Layers',
  },
  disabledAnalysisModules: [], //'VIIRS_FIRES', 'GLAD_ALERTS', 'TC_LOSS', 'IFL', 'LCC'
  layerPanel: {
    GROUP_WEBMAP: {
      order: 2,
      label: {},
      layers: [],
    },
    GROUP_TEST: {
      groupType: 'default',
      order: 1,
      label: {
        en: 'TEST Layers',
        fr: '',
        es: '',
        pt: '',
        id: '',
        zh: '',
        ka: '',
        hy: '',
        az: '',
        nl: '',
      },
      layers: [
        {
          id: 'CARBON_SEQ',
          order: 1,
          type: 'remoteDataLayer',
          uuid: 'e7208398-0acd-4f73-a824-c4fe1e356e0c',
        },
        {
          order: 2,
          id: 'states',
          type: 'wms',
          url: 'https://ahocevar.com/geoserver/wms',
          layerName: 'states',
          visible: false,
          label: {
            en: 'States Population',
          },
          legendConfig: {
            type: 'gradient',
            name: {
              en: 'Development Threat Index_Agricultural Expansion',
              fr: '',
              es: '',
              pt: '',
              id: '',
              zh: '',
              ka: '',
            },
            source: '',
            items: [
              {
                name: {
                  zh: 'Low',
                  pt: 'Low',
                  ka: 'Low',
                  id: 'Low',
                  fr: 'Low',
                  es: 'Low',
                  en: 'Low',
                },
                color: '#EFEADB',
              },
              {
                name: {
                  zh: '',
                  pt: '',
                  ka: '',
                  id: '',
                  fr: '',
                  es: '',
                  en: '',
                },
                color: '#B77B72',
              },
              {
                name: {
                  zh: 'High',
                  pt: 'High',
                  ka: 'High',
                  id: 'High',
                  fr: 'High',
                  es: 'High',
                  en: 'High',
                },
                color: '#78596E',
              },
            ],
          },
        },
      ],
    },

    extraLayers: [
      {
        id: 'MASK',
        type: 'dynamic',
        order: 10000,
        url: 'https://gis.forest-atlas.org/server/rest/services/country_masks/country_mask_global/MapServer',
        opacity: 0.35,
        layerIds: [0],
      },
      {
        id: 'LEGEND_LAYER',
        type: 'dynamic',
        url: 'https://gis-gfw.wri.org/arcgis/rest/services/legends/MapServer',
        visible: false,
        opacity: 0,
        layerIds: [],
      },
      {
        id: 'USER_FEATURES',
        type: 'graphic',
        visible: true,
      },
    ],
  },
};
