export default {
  webmap: 'de85e3fcc07948238aa6c1afd2a4ceb0',
  title: 'GFW Mapbuilder',
  subtitle: 'Make maps that matter',
  logoUrl: '',
  logoLinkUrl: '',
  aboutLinkUrl: '',
  downloadLinkUrl: '',
  printServiceUrl: 'https://gis.forest-atlas.org/server/rest/services/print/ExportWebMap/GPServer/Export%20Web%20Map',
  maskServiceUrl: '',
  mapThemeIds: '',
  mapThemes: '',
  narrative: '',
  hideHeader: false,
  hideFooter: false,
  includeMyGFWLogin: true,
  navLinksInNewTab: false,
  customColorTheme: '',
  language: 'en',
  useAlternativeLanguage: false,
  alternativeWebmap: '',
  alternativeLanguage: 'fr',
  alternativeLanguageTitle: 'Mapbuilder',
  alternativeLanguageSubtitle: 'Make maps that matter',
  alternativeMapThemes: '',
  alternativeNarrative: '',
  alternativeWebmapMenuName: 'Custom Layers',
  initialExtent: {
    x: null,
    y: null,
    z: null,
  },
  includeDocumentsTab: false,
  iso: '',
  viirsFires: true,
  intactForests: true,
  primaryForests: true,
  forma: false,
  aboveGroundBiomass: true,
  landCover: true,
  mangroves: false,
  sadAlerts: false,
  gladAlerts: true,
  gfwIntegratedAlertLayer: true,
  recentImagery: true,
  carbonSequence: true,
  carbonEmissions: true,
  treeCoverHeight: true,
  treeCover: true,
  treeCoverGain: true,
  treeCoverLoss: true,
  treeMosaicLandscapes: true,
  forestCarbonGrossRemovals: true,
  forestCarbonGrossEmissions: true,
  forestCarbonNetFlux: true,
  umdLandCover: true,
  drySpells: true,
  airQuality: true,
  windSpeed: true,
  webmapMenuName: 'Custom Layers',
  sharinghost: 'https://www.arcgis.com',
  analyticsCode: '',
  includeCartoTemplateLayers: false,
  cartoUser: 'wri-01',
  cartoTemplateId: 'tpl_07c315f8_c13e_11e4_b457_0e8dde98a187',
  cartoApiKey: 'your key here',
  cartoGroupLabel: {
    en: 'Carto Layers',
    fr: 'Carto Layers',
  },
  disabledAnalysisModules: [], //'VIIRS_FIRES', 'GLAD_ALERTS', 'TC_LOSS', 'IFL', 'LCC'
  layerPanel: {
    GROUP_WEBMAP: {
      order: 2,
      label: {},
      layers: [],
    },
    GROUP_TEST: {
      order: 1,
      groupType: 'default',
      label: {
        en: 'Tiled Layer',
      },
      layers: [
        {
          order: 3,
          id: 'drivers_of_defor',
          type: 'tiled',
          url: 'https://tiles.arcgis.com/tiles/hBEMHCkbQdfV906F/arcgis/rest/services/Drivers/MapServer',
          layerIds: [0],
          label: {
            en: 'Drivers',
          },
          legendConfig: {
            name: {
              ka: 'GLAD შეტყობინებები',
              zh: 'GLAD 预警',
              id: 'Peringatan GLAD',
              pt: 'Alertas GLAD',
              es: 'Alertas GLAD',
              fr: 'Alertes GLAD',
              en: 'GLAD Alerts',
            },
            type: 'basic',
            items: [
              {
                outlineColor: '#555555',
                color: '#DC6699',
                name: {
                  ka: 'GLAD შეტყობინებები',
                  zh: 'GLAD 预警',
                  id: 'Peringatan GLAD',
                  pt: 'Alertas GLAD',
                  es: 'Alertas GLAD',
                  fr: 'Alertes GLAD',
                  en: 'GLAD Alerts',
                },
              },
              {
                outlineColor: '#555555',
                color: '#e4c600',
                name: {
                  ka: 'ბოლო შეტყობინებები',
                  zh: '最近的提醒',
                  id: 'Lansiran Terbaru',
                  pt: 'Alertas Recentes',
                  es: 'Alertas recientes',
                  fr: 'Alertes récentes',
                  en: 'Recent Alerts',
                },
              },
            ],
          },
        },
      ],
    },
    extraLayers: [
      {
        id: 'MASK',
        type: 'dynamic',
        order: 10000,
        url: 'https://gis.forest-atlas.org/server/rest/services/country_masks/country_mask_global/MapServer',
        opacity: 0.35,
        layerIds: [0],
      },
      {
        id: 'LEGEND_LAYER',
        type: 'dynamic',
        url: 'https://gis-gfw.wri.org/arcgis/rest/services/legends/MapServer',
        visible: false,
        opacity: 0,
        layerIds: [],
      },
      {
        id: 'USER_FEATURES',
        type: 'graphic',
        visible: true,
      },
    ],
  },
};
