export default {
  order: 11,
  layerGroupId: 'GROUP_LCD',
  dataLayer: {
    id: 'INPE_CERRADO_PRODES',
    order: 11,
    type: 'remoteDataLayer',
    uuid: 'a2d9e60f-b4f6-4e56-8100-00fb3da2cf8e',
    groupId: 'GROUP_LCD',
  },
  layer: {
    sublabel: {
      ka: 'annual, 6.25ha, Legal Amazon / Cerrado, INPE',
      zh: '每年, 6.25ha, Legal Amazon / Cerrado, INPE',
      id: 'tahunan, 6.25ha, Legal Amazon / Cerrado, INPE',
      pt: 'წლიური, 6.25ha, Legal Amazon / Cerrado, INPE',
      es: 'anual, 6.25ha, Legal Amazon / Cerrado, INPE',
      fr: 'annuelle, 6.25ha, Legal Amazon / Cerrado, INPE',
      en: 'annual, 6.25ha, Legal Amazon / Cerrado, INPE',
    },
    label: {
      ka: 'PRODES ტყის გაჩეხვის',
      zh: 'PRODES 滥伐',
      id: 'PRODES Deforestasi',
      pt: 'PRODES Desmatamento',
      es: 'PRODES Deforestación',
      fr: 'PRODES Déforestation',
      en: 'PRODES Deforestation',
    },
    technicalName: 'inpe_cerrado_prodes',
    url: 'https://tiles.globalforestwatch.org/inpe_cerrado_prodes/v2021/default/root.json',
    type: 'Vector.Layer',
    id: 'INPE_CERRADO_PRODES',
    metadata: {
      metadata: null,
      legendConfig: {
        items: [
          {
            name: {
              en: 'PRODES Deforestation',
              fr: 'PRODES Déforestation',
              es: 'PRODES Deforestación',
              pt: 'PRODES Desmatamento',
              id: 'PRODES Deforestasi',
              zh: 'PRODES 滥伐',
              ka: 'PRODES ტყის გაჩეხვის',
            },
            color: '#C92A6D',
            outlineColor: '#C92A6D',
          },
        ],
        source: '',
        notes: [''],
        name: {
          en: 'PRODES Deforestation',
          fr: 'PRODES Déforestation',
          es: 'PRODES Deforestación',
          pt: 'PRODES Desmatamento',
          id: 'PRODES Deforestasi',
          zh: 'PRODES 滥伐',
          ka: 'PRODES ტყის გაჩეხვის',
        },
        type: 'basic',
      },
      interactionConfig: {},
    },
    style: 'https://tiles.globalforestwatch.org/inpe_cerrado_prodes/v2021/default/root.json',
  },
  isMetadataError: false,
  isError: false,
};
